### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by methanoid** [1alessandro1/HP-Prodesk-600-G1-SFF-macOS#10]
Brilliant work and thanks for sharing!! :-)

Will you be updating this for the newer OpenCore versions? Must be due one...  (and maybe for Ventura) ??

**Comment by 1alessandro1** [comment]
Hello, I've now more free time after the exams have finished...

Since I'm using this PC as my home server right now I might provide an update but you need to test it @methanoid  are you able to do it?

**Comment by methanoid** [comment]
Sorry, sold my machines

**Comment by Kadibuntu** [comment]
I would like to test the update

**Comment by robi62** [comment]
hi did you manage to update efi for Ventura??I just bought same pc???
