### ISSUE TITLE
Crash when waking from sleep

### ISSUE THREAD

**Issue by jeff-h** [1alessandro1/HP-Prodesk-600-G1-SFF-macOS#2]
The only issue I'm seeing with this EFI on my 600 G1 is that it sleeps fine, and indeed wakes up fine, but then it immediately restarts.

Do you have sleep wake working?

**Comment by 1alessandro1** [comment]
Yes I managed to have working sleep, try to follow what I suggested in issue 1.

**Comment by 1alessandro1** [comment]
Check answer from issue 1
