### ISSUE TITLE
Just upgraded my 600 G1 to Monterey

### ISSUE THREAD

**Issue by jeff-h** [1alessandro1/HP-Prodesk-600-G1-SFF-macOS#3]
Cloned your current release, updated the kexts as instructed, generated new iMac16,1 serials etc and it has all worked out of the box. Thanks so much again for sharing your work on this! 🎉

**Comment by 1alessandro1** [comment]
Amazing! Thank you for posting this, it makes me think that my efforts are worth for somebody :)

Anyway for christmas I'll update to the 0.7.6 release which will be coming next month, when I'll be back home from university
