### ISSUE TITLE
Only option in opencore is "Reset NVRAM"

### ISSUE THREAD

**Issue by stefan-vasilescu** [1alessandro1/HP-Prodesk-600-G1-SFF-macOS#8]
I have followed every instruction in the opencore installation guide and I have edited config.plist and it's still doing that. Help

**Comment by MichaelTrip** [comment]
I have the same problem.

**Comment by 1alessandro1** [comment]
I will update the EFI soon, who is able to test it? I'm using this PC as my home server right now, so I cannot boot macOS on it

**Comment by 1alessandro1** [comment]
anyway it was the Scanpolicy Value to set to 0

https://github.com/1alessandro1/HP-Prodesk-600-G1-SFF-macOS/blob/91f3f178dfdc976c6f53eacd167ba9e91f4beca0/EFI/OC/config.plist#L674
