### ISSUE TITLE
vault enabled???

### ISSUE THREAD

**Issue by robi62** [1alessandro1/HP-Prodesk-600-G1-SFF-macOS#9]
hi I was trying to test your EFI but I get message about vault???I have never seen anything like this before..
What do I need to do ???
Regards roberto

**Comment by 1alessandro1** [comment]
Hello, you need to edit this lines replacing "Secure" with "Optional" if you don't want to use OpenCore's Vault feature

https://github.com/1alessandro1/HP-Prodesk-600-G1-SFF-macOS/blob/91f3f178dfdc976c6f53eacd167ba9e91f4beca0/EFI/OC/config.plist#L678-L679

**Comment by robi62** [comment]
Ok thanks
